Added random emoji generator made using HTML, CSS and Javascript
Grow-with-Open-Source/Javascript-Projects pull request #16
Opened 2023-10-30 16:30 UTC by urjabahad

2023-10-30 18:49 UTC, iamwatchdogs requested changes
Please make the requested changes.

2023-10-30 18:49 UTC, iamwatchdogs commented on EmojiGenerator/index.html
> +</script>
Hey @urjabahad, Please make a separate js file for this small piece of code.

```suggestion
<!-- All JS code will be within script.js" -->
<script src="script.js"></script>
```

2023-10-30 18:59 UTC, urjabahad commented
done changes. pls check.thank you

2023-10-31 01:12 UTC, iamwatchdogs approved these changes
Requested Changes have been made. Reviewed and Approved by @iamwatchdogs.

2023-10-31 01:13 UTC, merged

2023-10-31 01:14 UTC, iamwatchdogs commented
Thank you for contributing, @urjabahad. Please check your contribution on [GitHub Pages](https://grow-with-open-source.github.io/Javascript-Projects/).