Added E Commerce website
Grow-with-Open-Source/Javascript-Projects pull request #6
Opened 2023-10-25 04:15 UTC by rahulch-1

This is an E-Commerce Website made using HTML, CSS, JavaScript which has products with their description and their reviews.

2023-10-25 09:04 UTC, iamwatchdogs commented
@rahulch-1 Please make the required changes to pass the lining checks, so that we can review and merge your PR. And don't worry about the files that end with `**.min.js` as the eslinter configs have been updated to ignore those files.

2023-10-25 09:18 UTC, iamwatchdogs requested changes
Please make the requested changes

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/.github/ISSUE_TEMPLATE/bug.yaml
- [ ] Please remove the `.github`  directory and all the files within it.

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/css/.DS_Store
- [ ]  Remove all `.DS_Store` file present anywhere within your project.

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/js/.DS_Store
- [ ] Remove all `.DS_Store` files present within your project.

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/js/about.js
- [ ] Fix your code to pass the lining checks *(about.js)*.

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/js/revolution/.DS_Store
- [ ] Remove all the `.DS_Store` files present within your projects.

2023-10-25 09:18 UTC, iamwatchdogs commented on E-commerce website/js/revolution/js/.DS_Store
- [ ] Remove all `.DS_Store` files within your projects.

2023-10-25 09:21 UTC, iamwatchdogs commented on E-commerce website/Readme.md
(Optional) Can you add a small description explaining your project to others?

2023-10-25 09:23 UTC, iamwatchdogs commented on E-commerce website/js/revolution/css/openhand.html
> [!IMPORTANT]
> If this file is empty and does nothing, make sure to remove it.

2023-10-25 09:23 UTC, iamwatchdogs commented on E-commerce website/js/revolution/css/closedhand.html
> [!IMPORTANT]
> If this file is empty and does nothing, make sure to remove it.

2023-10-29 05:23 UTC, iamwatchdogs commented
@rahulch-1 don't worry about the lining checks for now, as the only issues that are reported for creating unused variables _(which were used in other files)_ and not recognising the jquery syntax.

2023-10-29 05:32 UTC, iamwatchdogs requested changes
@rahulch-1 The only changes that were made to resolve the code review issue is to remove a single `.DS_Store` file from your projects. You still need to make the following changes:

- [ ] Remove the directory/file names `.github`.
- [ ] Remove all `.DS_Store` files.
- [ ] Reply to the previously mentioned comments about `openhand.html` and `close hand.html` _(You can find them in our PR conversation)_

> [!NOTE]
> Don't worry about the linting checks as we're ignoring them for your case. Just make the above mentioned changes.

2023-10-29 05:41 UTC, rahulch-1 commented on E-commerce website/js/revolution/css/closedhand.html
Done @iamwatchdogs I removed those unused html files

2023-10-29 05:42 UTC, rahulch-1 commented
Now I removed the .github directory and all the .DS_Store files also

2023-10-29 05:43 UTC, rahulch-1 commented
Thanks for helping me out

2023-10-29 05:44 UTC, iamwatchdogs commented
@rahulch-1 you have indeed removed `.github` directory but you haven't removed all `.DS_Store` file.

2023-10-29 05:46 UTC, iamwatchdogs commented
All of these remaining `.DS_Store` file paths are mentioned in previous code review that are present in this conversation.

2023-10-29 05:57 UTC, rahulch-1 commented
Sorry, but I am not able to find any .DS_store files now

2023-10-29 06:07 UTC, iamwatchdogs commented
> Thanks for helping me out

It's okay @rahulch-1. Just so you know, this linter makes sure each and every file maintains its integrity and works as intended without any syntactical errors. In some cases, the linter that we have used checks purely for JavaScript and doesn't recognise any external framework. This is the reason why people set up linter within their projects that are built using frameworks, as these linter will be configured according to the framework avoiding any linting issues. And the way we configured our linter for this repo is for pure javascript files and not medium to big projects built using frameworks like React. 

We respect your patience and willing to contribute, but I, @iamwatchdogs, as the main maintainer have to make sure you give the best from your side while maintaining the whole integrity of the repo. So, please have some patience as when we request to make a few changes. Hope this helps you understand what we at @Grow-with-Open-Source are trying to do.

2023-10-29 06:12 UTC, iamwatchdogs commented
> Sorry, but I am not able to find any .DS_store files now

Sorry for that @rahulch-1, Yes all the files were removed.

2023-10-29 06:17 UTC, iamwatchdogs approved these changes
Request Changes were made. Reviewed and Approved by @iamwatchdogs.

2023-10-29 06:18 UTC, merged

2023-10-29 06:19 UTC, rahulch-1 commented
yes, @iamwatchdogs I completely understand the need for a specialized linter setup

2023-10-29 06:24 UTC, iamwatchdogs commented
Thank you for contributing, @rahulch-1. Please check your contribution on [GitHub Pages](https://grow-with-open-source.github.io/Javascript-Projects/).